// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/dev-login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/dev-login.post').default>>>>
    }
    '/api/auth/google': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/google.post').default>>>>
    }
    '/api/auth/login-event': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login-event.post').default>>>>
    }
    '/api/dashboard/summary': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/summary.get').default>>>>
    }
    '/api/gym-profile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/gym-profile/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/gym-profile/index.post').default>>>>
    }
    '/api/instructors': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/instructors/index.get').default>>>>
    }
    '/api/members/:id': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members/[id].put').default>>>>
    }
    '/api/members': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members/index.post').default>>>>
    }
    '/api/memberships': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/memberships/index.get').default>>>>
    }
    '/api/pos/checkout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pos/checkout.post').default>>>>
    }
    '/api/pos/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pos/products/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/pos/products/index.post').default>>>>
    }
    '/api/reports/attendance': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/attendance.get').default>>>>
    }
    '/api/reports/revenue': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/revenue.get').default>>>>
    }
    '/api/schedule': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/schedule/index.get').default>>>>
    }
    '/api/transactions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/transactions/index.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}